### ISSUE TITLE
Expand README.md with details for a build environment

### ISSUE THREAD

**Issue by theMK2k** [MobyGamer/total-dos-launcher#34]
Hey Jim,

could you please expand README.md or any other textfile with informations on how to setup a build environment to successfully build TDL from source?

Thanks :)

**Comment by MobyGamer** [comment]
I've done so; is that enough for you, or do you need additional information?

**Comment by MobyGamer** [comment]
Feel free to re-open this if you can't build TDL.

**Comment by theMK2k** [comment]
Will do, thanks!
