### ISSUE TITLE
Allow user-defined Header

### ISSUE THREAD

**Issue by theMK2k** [MobyGamer/total-dos-launcher#41]
Currently, TDL shows the header "The Total DOS Launcher".

It would be great to have an optional user-defined (TDL.INI) header. E.g. "The Total DOS Launcher - Action Games" where "Action Games" is the user defined header.

Also, TDL can be a great launcher for collections e.g. "The Total DOS Launcher - id Anthology Vintage" having selectable items:
>    Catacomb 3-D
>    Commander Keen: Invasion of the Vorticons
>    Commander Keen: Goodbye Galaxy
...
>    Wolfenstein 3D

a user-defined header would be very helpful here.

**Comment by MobyGamer** [comment]
Should be trivial to put in TDL.INI.  I'll work on it the next time I touch the code.
