### ISSUE TITLE
TDL.INI: Allow proglocations exceeding 80 chars

### ISSUE THREAD

**Issue by theMK2k** [MobyGamer/total-dos-launcher#42]
In order to utilize TDL for launching executables within subdirectories, the current DOS limitations which cap the proglocations string at 80 characters quickly become an issue.

id Anthology - Vintage for example would need 149 characters: "..;..\CAT3D;..\CATACOMB;..\DAVE;..\HOVER;..\KDREAMS;..\KEEN123;..\KEEN4;..\KEEN5;..\KEEN6;..\ROVER1;..\ROVER2;..\SHADOW;..\SLORDAX;..\SPEAR;..\WOLF3D"

Would there be any chance to increase the cap? Maybe by having:

````
proglocations=..;..\CAT3D;..\CATACOMB;..\DAVE;..\HOVER;..\KDREAMS;..\KEEN123;..\KEEN4
proglocations1=..\KEEN5;..\KEEN6;..\ROVER1;..\ROVER2;..\SHADOW;..\SLORDAX;..\SPEAR;..\WOLF3D
````

or even

````
proglocation=..
proglocation=..\CAT3D
proglocation=..\CATACOMB
proglocation=..\DAVE
proglocation=..\HOVER
proglocation=..\KDREAMS
proglocation=..\KEEN123
proglocation=..\KEEN4
proglocation=..\KEEN5
proglocation=..\KEEN6
proglocation=..\ROVER1
proglocation=..\ROVER2
proglocation=..\SHADOW
proglocation=..\SLORDAX
proglocation=..\SPEAR
proglocation=..\WOLF3D
````

**Comment by MobyGamer** [comment]
The limitation is definitely a DOS limitation as I'm using DOS PATH constructs. But the real reason I'm leaning towards closing this as wontfix is because the point of TDL is to eliminate the micromanagement and manual setup of loading games. In other words, I'm confused by the need to put each game in it's own subdir when TDL creates them for you.

**Comment by theMK2k** [comment]
Regarding the *id Anthology - Vintage* CD. When you install its games with the default options, you end up with the directory structure seen above.

Using TDL in that way also brings another risk: you could for example end up with multiple START.BAT files which you have to differentiate. So in the end, I tackle these issues outside TDL as documented here: https://documentation.metropolis-launcher.net/create_total_dos_launcher_menu.htm (scroll down to Behind the Scenes).
