### ISSUE TITLE
TDL.EXE - Runtime error 161 at 1BDC:02C1

### ISSUE THREAD

**Issue by JamesSWiggins** [MobyGamer/total-dos-launcher#54]
I receive this error when launching TDL.EXE on several different authentic hardware DOS systems.  I'm using the latest TDL.EXE from GitHub.  What causes this?

**Comment by Krathoon** [comment]
Ah. I got the same error. Running on MS DOS.

**Comment by Krathoon** [comment]
Does it have to be DOS 7?

**Comment by MobyGamer** [comment]
Apologies for the very delayed response; somehow I didn't see these notifications.

Runtime error 161 is "default fault while reading", so assuming you don't have any storage read issues, let me know what the full environment is you're trying to run it on (DOS version, hardware, where the files are located, etc.).

Just in case there was an issue with the previous binary, I've just now uploaded a new .EXE to the repo, so grab that from the distro/ directory and see if that helps.  You can also run tdl with -d for debug output, and also print the tdl.log file here if it is created.

**Comment by MobyGamer** [comment]
For completeness, I also updated the newest release to 0.1.5 so that the readme is accurate.

**Comment by MobyGamer** [comment]
@JamesSWiggins Were you ever able to figure out the issue?  I'm guessing it might have been running (or addressing) read-only media?

If you'd still like to troubleshoot this, let me know what your environment is:  Storage, DOS version, etc.

**Comment by MobyGamer** [comment]
Closing due to lack of user input.  If you're still having this issue, re-open and let me know what you've tried.
